apiVersion: 1

deleteDatasources:
  - name: prometheus-test
    orgId: 1

datasources:
- name: prometheus-test
  type: prometheus
  access: proxy
  orgId: 1
  url: http://localhost:9090
  isDefault: true
  version: 1
  editable: false
  basicAuth: false