apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: production
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: sergej1024/frontend:latest
        imagePullPolicy: IfNotPresent
        name: frontend
        env:
          - name: BASE_URL
            value: http://backend:9000
        volumeMounts:
          - mountPath: "/tmp/cache"
            name: static-storage
      volumes:
        - name: static-storage
          persistentVolumeClaim:
            claimName: static-storage-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: production
spec:
  type: ClusterIP
  ports:
  - name: frontend
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
