apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-storage-pv
  namespace: production
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv