kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-storage-pvc
  namespace: production
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi