---
apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: first
spec:
  environments:
    default:
      defaultNamespace: default
      server: https://158.160.46.9:6443
    stage:
      defaultNamespace: stage
      server: https://158.160.46.9:6443
    prod:
      defaultNamespace: prod
      server: https://158.160.46.9:6443
      includes:
        - endpoint
  vars: {}
  excludes:
    - endpoint
