resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    ll:
  hosts:
    cp1:
      ansible_host: ${yandex_compute_instance.control-plane[*].network_interface.0.nat_ip_address}
      ansible_user: ansible
    node1:
      ansible_host: ${yandex_compute_instance.worker-foreach[*].network_interface.0.nat_ip_address}
      ansible_user: ansible
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        cp1:
        node1:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  DOC
  filename = "kubespray/inventory/mycluster/inventory.ini"

   depends_on = [
   yandex_compute_instance.control-plane,
   yandex_compute_instance.worker-foreach
 ]
}  
# resource "local_file" "all_vars" {
#   content = <<-DOC
#   # Ansible vars containing variable values from Terraform.
#   # Generated by Terraform.

#     clickhouse_01_ext_ip: ${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
#     vector_01_ext_ip: ${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
#   DOC
#   filename = "../infrastructure/group_vars/all.yml"

#  depends_on = [
#    yandex_compute_instance.node01,
#    yandex_compute_instance.node02
#  ]
# }