---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: communication-accept-pods
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: hello-node
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: hello-node
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: hello-node