---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-{{ .Release.Name }}
  name: backend-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.backend.type }}
  ports:
  - name: backend-{{ .Release.Name }}
    port: {{ .Values.backend.port | default 9000}}
    protocol: TCP
    targetPort: {{ .Values.backend.port | default 9000}}
  selector:
    app: backend-{{ .Release.Name }}
