---
apiVersion: v1
kind: Service
metadata:
  name: db-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port | default 5432 }}
      targetPort: {{ .Values.postgres.port | default 5432 }}
  selector:
    app: db-{{ .Release.Name }}
