---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-{{ .Release.Name }}
  name: frontend-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.frontend.type }}
  ports:
  - name: frontend-{{ .Release.Name }}
    port: {{ .Values.frontend.port | default 80 }}
    protocol: TCP
    targetPort: {{ .Values.frontend.port | default 80 }}
  selector:
    app: frontend-{{ .Release.Name }}